apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort # Change this to LoadBalancer if you are using a cloud provider
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30006 # Specify a NodePort if needed
  selector:
    app: api-gateway
