apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: NodePort # Change this to LoadBalancer if you are using a cloud provider
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30004 # Specify a NodePort if needed
  selector:
    app: login-service
