stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/api-gateway"
  DOCKER_TAG: "$CI_COMMIT_SHA"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:latest ./path/to/api-gateway
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f ./k8s/deployment.yaml
    - kubectl apply -f ./k8s/service.yaml
  only:
    - main
