version: '1.0.0'

services:
  api-gateway:
    build: 
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Adjust the port as needed
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  login:
    build: 
      context: ./backend/login-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002" # Adjust the port as needed
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      MONGO_URI:  mongodb+srv://madathingalafsal:Afsal%40090797@OURSHOP.mkqpdg9.mongodb.net/login-service

  signup:
    build: 
      context: ./backend/signup-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Adjust the port as needed
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      MONGO_URI:  mongodb+srv://madathingalafsal:Afsal%40090797@OURSHOP.mkqpdg9.mongodb.net/signup-service

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq-forloginserivce
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   RABBITMQ_DEFAULT_USER: user
    #   RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5


networks:
  default:
    name: microservice_network
